### ISSUE TITLE
Do you welcome contributions? 

### ISSUE THREAD

**Issue by RitheshKumar** [hollance/TheKissOfShame#1]
Hey, this is unsolicited. I'm an Audio DSP guy & this project is exciting! I would love to contribute if you're open to it. I can come in at algorithm implementation, at the audio backend. 

My background: https://www.linkedin.com/in/ritheshkumar/ 

What say?

**Comment by hollance** [comment]
Hi Ritesh, I'm currently patching up the code so it builds and runs with JUCE 7. There will be many improvements to be made, for example the plug-in parameters are not exposed to the host right now. However, I don't know yet exactly what needs to happen. Once the to-do list is clearer, I think it would be great to have contributions, but right now it's a little too early. Thanks for the offer!

**Comment by RitheshKumar** [comment]
Thanks for the heads up. Please keep me posted. All the best!

**Comment by hollance** [comment]
Hi @RitheshKumar, I (mostly) finished going through the code and figuring out a to-do list. Feel free to pick anything from that list to work on, or just play with the code. And let me know if you find any new bugs. 😄

**Comment by RitheshKumar** [comment]
On it @hollance ! :) Will keep you posted, thanks
