### ISSUE TITLE
Automating a parameter makes the other controls on the GUI go sluggish

### ISSUE THREAD

**Issue by heebje** [hollance/TheKissOfShame#12]
When I automate e.g. the 'Shame' parameter in Reaper, the other controls become slow, sluggish to operate, with a very noticeable lag.

I have not noticed this in other plugins, so it must be something that can be avoided.

https://github.com/hollance/TheKissOfShame/assets/16598068/ff3f311b-0b5f-418b-8c52-b5f0b4b5000b

**Comment by hollance** [comment]
Interesting! Does this happen too when the animation is not playing? You can try this by double-clicking the background to remove the reels.

**Comment by heebje** [comment]
> Interesting! Does this happen too when the animation is not playing? You can try this by double-clicking the background to remove the reels.

No...
And the problem as a whole seems to have gone away now...

I did do a Windows reboot (for other reasons), and now I cannot replicate the sluggish behaviour anymore.

Closing this.

I will reopen if I encounter the problem again (replicably).

**Comment by hollance** [comment]
The animation is pretty resource intensive, though. It looks cool but it eats up a lot of CPU. 😅
