### ISSUE TITLE
Small GUI glitch (probably entirely cosmetic)

### ISSUE THREAD

**Issue by heebje** [hollance/TheKissOfShame#3]
Very small GUI glitch in the "Shame" knob, when operated from outside the GUI:

![tkos](https://github.com/hollance/TheKissOfShame/assets/16598068/45fa37c7-230e-4c13-a824-51e435f6e275)

Otherwise: What an awesome plugin!!! https://youtu.be/PWO9IvaoiRU

**Comment by hollance** [comment]
Thanks @heebje. You're right that it's purely cosmetic. A fix is in the works. Thanks for reporting!

**Comment by heebje** [comment]
Dank je wel! Geweldige plugin. Helemaal goed.
